### ISSUE TITLE
ActionProvider throws if code can't be parsed

### ISSUE THREAD

**Issue by tjx666** [nicoespeon/abracadabra#87]
## Describe the bug

When I write following code:

![screenshot_2020-03-11_18-44-56](https://user-images.githubusercontent.com/41773861/76408769-707bec00-63c8-11ea-9377-dc9d59b44fbf.png)

error message: 
```
Unexpected token (29:4): SyntaxError: Unexpected token (29:4)
	at Object.raise (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:657452)
	at Object.unexpected (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:677107)
	at Object.parseExprAtom (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:698149)
	at Object.parseExprAtom (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:575944)
	at Object.parseExprSubscripts (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:690154)
	at Object.parseMaybeUnary (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:689746)
	at Object.parseMaybeUnary (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:646315)
	at Object.parseExprOps (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:687156)
	at Object.parseMaybeConditional (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:686688)
	at Object.parseMaybeAssign (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:685576)
	at Object.parseMaybeAssign (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:645779)
	at Object.parseObjectProperty (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:706149)
	at Object.parseObjPropValue (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:706631)
	at Object.parseObjPropValue (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:644824)
	at Object.parseObjectMember (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:704931)
	at Object.parseObj (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:703762)
	at Object.parseExprAtom (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:697112)
	at Object.parseExprAtom (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:575944)
	at Object.parseExprSubscripts (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:690154)
	at Object.parseMaybeUnary (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:689746)
	at Object.parseMaybeUnary (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:646315)
	at Object.parseExprOps (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:687156)
	at Object.parseMaybeConditional (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:686688)
	at Object.parseMaybeAssign (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:685576)
	at Object.parseMaybeAssign (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:645779)
	at Object.parseObjectProperty (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:706149)
	at Object.parseObjPropValue (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:706631)
	at Object.parseObjPropValue (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:644824)
	at Object.parseObjectMember (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:704931)
	at Object.parseObj (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:703762)
	at Object.parseExprAtom (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:697112)
	at Object.parseExprAtom (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:575944)
	at Object.parseExprSubscripts (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:690154)
	at Object.parseMaybeUnary (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:689746)
	at Object.parseMaybeUnary (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:646315)
	at Object.parseExprOps (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:687156)
	at Object.parseMaybeConditional (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:686688)
	at Object.parseMaybeAssign (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:685576)
	at Object.parseMaybeAssign (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:645779)
	at Object.parseVar (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:728033)
	at Object.parseVarStatement (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:724611)
	at Object.parseStatementContent (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:717106)
	at Object.parseStatementContent (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:641972)
	at Object.parseStatement (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:715840)
	at Object.parseBlockOrModuleBlockBody (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:726551)
	at Object.parseBlockBody (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:726360)
	at Object.parseTopLevel (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:714491)
	at Object.parse (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:743906)
	at Object.t.parse (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:745123)
	at Object.parse (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:1040107)
	at Object.t.parse (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:1281972)
	at Object.y [as parse] (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:1040079)
	at t.RefactoringActionProvider.provideCodeActions (c:\Users\YuTengjing\.vscode\extensions\nicoespeon.abracadabra-3.2.1\out\extension.js:1:1345737)
	at c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:586:864
	at c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:54:345
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:54:317)
	at T.provideCodeActions (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:586:835)
	at c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:609:631
	at V._withAdapter (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:604:832)
	at V.$provideCodeActions (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:609:609)
	at p._doInvokeHandler (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:688:464)
	at p._invokeHandler (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:688:156)
	at p._receiveRequest (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:686:766)
	at p._receiveOneMessage (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:685:623)
	at c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:683:791
	at l.fire (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:845)
	at v.fire (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:191:325)
	at c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:851:104
	at l.fire (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:845)
	at v.fire (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:191:325)
	at t.PersistentProtocol._receiveMessage (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:195:717)
	at c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:192:897
	at l.fire (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:845)
	at p.acceptChunk (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:897)
	at c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:249
	at Socket.t (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:197:232)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

## How to reproduce

write following code:

```typescript
const obj = {
    a:
}
```

## Expected behavior

no error message

## Additional information

- Version of the extension impacted: _vX.X.X_

Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363_

**Comment by nicoespeon** [comment]
Hi @tjx666 👋 

Thanks for reporting that. Indeed, if code can't be parsed the extension doesn't catch the error and throws in the console. It's noisy, we should stop that.

Today, there's a try/catch here: https://github.com/nicoespeon/abracadabra/blob/0aea60ed14807e21ae2ef0b4d32401661ab3d07d/src/action-providers.ts#L34-L39

But that's too late. It should happen here: https://github.com/nicoespeon/abracadabra/blob/0aea60ed14807e21ae2ef0b4d32401661ab3d07d/src/action-providers.ts#L21

We're currently working on this action provider file (#80, #81 and #82) to improve performances. Thus, we'll tackle this just after.

Hopefully it's not a critical bug. But it's annoyingly noisy in the dev console.

**Comment by nicoespeon** [comment]
@all-contributors please add tjx666 for bug

**Comment by nicoespeon** [comment]
FYI, this can be tackled now. We should basically try/catch earlier, as I said in my previous comment.
